# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_w(object):
    def setupUi(self, main_w):
        main_w.setObjectName("main_w")
        main_w.resize(705, 534)
        main_w.setStyleSheet("background:rgb(38, 66, 32);\n"
"color:rgb(4, 8, 244);")
        self.centralwidget = QtWidgets.QWidget(main_w)
        self.centralwidget.setObjectName("centralwidget")
        self.list_wid = QtWidgets.QListWidget(self.centralwidget)
        self.list_wid.setGeometry(QtCore.QRect(0, 300, 311, 191))
        self.list_wid.setStyleSheet("border:2px solid white;\n"
"border-radius:5px;")
        self.list_wid.setObjectName("list_wid")
        self.findnote_btn = QtWidgets.QLineEdit(self.centralwidget)
        self.findnote_btn.setGeometry(QtCore.QRect(330, 20, 361, 21))
        self.findnote_btn.setStyleSheet("border:2px solid white;\n"
"border-radius:5px;")
        self.findnote_btn.setObjectName("findnote_btn")
        self.teg_wid = QtWidgets.QListWidget(self.centralwidget)
        self.teg_wid.setGeometry(QtCore.QRect(0, 20, 311, 171))
        self.teg_wid.setStyleSheet("border:2px solid white;\n"
"border-radius:5px;")
        self.teg_wid.setObjectName("teg_wid")
        self.savenote_btn = QtWidgets.QPushButton(self.centralwidget)
        self.savenote_btn.setGeometry(QtCore.QRect(330, 420, 181, 31))
        self.savenote_btn.setStyleSheet("border:2px solid rgb(0, 0, 0);\n"
"border -radiius:5px;")
        self.savenote_btn.setObjectName("savenote_btn")
        self.findteg_btn = QtWidgets.QLineEdit(self.centralwidget)
        self.findteg_btn.setGeometry(QtCore.QRect(160, 240, 151, 31))
        self.findteg_btn.setStyleSheet("border:2px solid rgb(0, 0, 0);\n"
"border-radius:5px;")
        self.findteg_btn.setObjectName("findteg_btn")
        self.teg_lb = QtWidgets.QLabel(self.centralwidget)
        self.teg_lb.setGeometry(QtCore.QRect(0, 0, 311, 20))
        self.teg_lb.setStyleSheet("border:2px solid white;\n"
"border-radius:5px;")
        self.teg_lb.setObjectName("teg_lb")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(330, 0, 361, 20))
        self.label_3.setStyleSheet("border:2px solid white;\n"
"border-radius:5px;")
        self.label_3.setObjectName("label_3")
        self.list_lb = QtWidgets.QLabel(self.centralwidget)
        self.list_lb.setGeometry(QtCore.QRect(0, 280, 311, 20))
        self.list_lb.setStyleSheet("border:2px solid white;\n"
"border-radius:5px;")
        self.list_lb.setObjectName("list_lb")
        self.delatenote_btn = QtWidgets.QPushButton(self.centralwidget)
        self.delatenote_btn.setGeometry(QtCore.QRect(520, 420, 171, 31))
        self.delatenote_btn.setStyleSheet("border:2px solid rgb(0, 0, 0);\n"
"border -radiius:5px;")
        self.delatenote_btn.setObjectName("delatenote_btn")
        self.createnote_btn = QtWidgets.QPushButton(self.centralwidget)
        self.createnote_btn.setGeometry(QtCore.QRect(330, 470, 361, 31))
        self.createnote_btn.setStyleSheet("border:2px solid rgb(0, 0, 0);\n"
"border -radiius:5px;")
        self.createnote_btn.setObjectName("createnote_btn")
        self.deleteteg_btn = QtWidgets.QPushButton(self.centralwidget)
        self.deleteteg_btn.setGeometry(QtCore.QRect(160, 200, 151, 31))
        self.deleteteg_btn.setStyleSheet("border:2px solid rgb(0, 0, 0);\n"
"border -radiius:5px;")
        self.deleteteg_btn.setObjectName("deleteteg_btn")
        self.saveteg_btn = QtWidgets.QPushButton(self.centralwidget)
        self.saveteg_btn.setGeometry(QtCore.QRect(0, 200, 151, 31))
        self.saveteg_btn.setStyleSheet("border:2px solid rgb(0, 0, 0);\n"
"border -radiius:5px;")
        self.saveteg_btn.setObjectName("saveteg_btn")
        self.createteg_btn = QtWidgets.QPushButton(self.centralwidget)
        self.createteg_btn.setGeometry(QtCore.QRect(0, 240, 151, 31))
        self.createteg_btn.setStyleSheet("border:2px solid rgb(0, 0, 0);;\n"
"border -radiius:5px;")
        self.createteg_btn.setObjectName("createteg_btn")
        self.note_wid = QtWidgets.QTextEdit(self.centralwidget)
        self.note_wid.setGeometry(QtCore.QRect(330, 50, 361, 361))
        self.note_wid.setStyleSheet("border:2px solid white;\n"
"border-radius:5px;")
        self.note_wid.setObjectName("note_wid")
        main_w.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(main_w)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 705, 21))
        self.menubar.setObjectName("menubar")
        main_w.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(main_w)
        self.statusbar.setObjectName("statusbar")
        main_w.setStatusBar(self.statusbar)

        self.retranslateUi(main_w)
        QtCore.QMetaObject.connectSlotsByName(main_w)

    def retranslateUi(self, main_w):
        _translate = QtCore.QCoreApplication.translate
        main_w.setWindowTitle(_translate("main_w", "EasyNote"))
        self.findnote_btn.setPlaceholderText(_translate("main_w", "Note name"))
        self.savenote_btn.setText(_translate("main_w", "SAVE"))
        self.findteg_btn.setPlaceholderText(_translate("main_w", "Teg name"))
        self.teg_lb.setText(_translate("main_w", "TEGS"))
        self.label_3.setText(_translate("main_w", "NOTES"))
        self.list_lb.setText(_translate("main_w", "LIST"))
        self.delatenote_btn.setText(_translate("main_w", "DELATE"))
        self.createnote_btn.setText(_translate("main_w", "CREATE"))
        self.deleteteg_btn.setText(_translate("main_w", "DELATE TEG"))
        self.saveteg_btn.setText(_translate("main_w", "SAVE TEG"))
        self.createteg_btn.setText(_translate("main_w", "CREATE TEG"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_w = QtWidgets.QMainWindow()
    ui = Ui_main_w()
    ui.setupUi(main_w)
    main_w.show()
    sys.exit(app.exec_())
